-- ==============================================================================
-- PySQL-Sync (Retailytics Pro) - Standard & Advanced SQL Analytics Queries
-- Multi-Dialect Compatible (MySQL 8.0+ & SQLite 3.25+)
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. List all unique cities where customers are located
-- ------------------------------------------------------------------------------
SELECT DISTINCT customer_city 
FROM customers 
ORDER BY customer_city ASC;

-- ------------------------------------------------------------------------------
-- 2. Count the number of orders placed in 2017
-- ------------------------------------------------------------------------------
-- MySQL:
-- SELECT COUNT(order_id) AS orders_2017 FROM orders WHERE YEAR(order_purchase_timestamp) = 2017;
-- Standard/SQLite:
SELECT COUNT(order_id) AS orders_2017 
FROM orders 
WHERE substr(order_purchase_timestamp, 1, 4) = '2017';

-- ------------------------------------------------------------------------------
-- 3. Total sales per product category
-- ------------------------------------------------------------------------------
SELECT 
    COALESCE(p.product_category_name, 'Unknown') AS product_category,
    ROUND(SUM(oi.price), 2) AS total_sales
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY total_sales DESC;

-- ------------------------------------------------------------------------------
-- 4. Percentage of orders paid in installments
-- ------------------------------------------------------------------------------
SELECT 
    ROUND((COUNT(DISTINCT CASE WHEN payment_installments > 1 THEN order_id END) * 100.0) / COUNT(DISTINCT order_id), 2) AS installment_order_pct
FROM payments;

-- ------------------------------------------------------------------------------
-- 5. Count of customers from each state
-- ------------------------------------------------------------------------------
SELECT 
    customer_state, 
    COUNT(customer_id) AS customer_count
FROM customers
GROUP BY customer_state
ORDER BY customer_count DESC;

-- ------------------------------------------------------------------------------
-- 6. Orders placed per month in 2018
-- ------------------------------------------------------------------------------
SELECT 
    substr(order_purchase_timestamp, 6, 2) AS month_num,
    COUNT(order_id) AS order_count
FROM orders
WHERE substr(order_purchase_timestamp, 1, 4) = '2018'
GROUP BY month_num
ORDER BY month_num ASC;

-- ------------------------------------------------------------------------------
-- 7. Average number of products per order, grouped by customer city
-- ------------------------------------------------------------------------------
WITH order_item_counts AS (
    SELECT 
        o.order_id,
        c.customer_city,
        COUNT(oi.order_item_id) AS items_in_order
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY o.order_id, c.customer_city
)
SELECT 
    customer_city,
    ROUND(AVG(items_in_order), 2) AS avg_products_per_order
FROM order_item_counts
GROUP BY customer_city
ORDER BY avg_products_per_order DESC;

-- ------------------------------------------------------------------------------
-- 8. Percentage of total revenue contributed by each product category
-- ------------------------------------------------------------------------------
WITH category_sales AS (
    SELECT 
        COALESCE(p.product_category_name, 'Unknown') AS category,
        SUM(oi.price) AS cat_revenue
    FROM products p
    JOIN order_items oi ON p.product_id = oi.product_id
    GROUP BY p.product_category_name
),
total_rev AS (
    SELECT SUM(cat_revenue) AS total_revenue FROM category_sales
)
SELECT 
    cs.category,
    ROUND(cs.cat_revenue, 2) AS category_revenue,
    ROUND((cs.cat_revenue * 100.0) / tr.total_revenue, 2) AS revenue_percentage
FROM category_sales cs
CROSS JOIN total_rev tr
ORDER BY cs.cat_revenue DESC;

-- ------------------------------------------------------------------------------
-- 9. Correlation between product price and purchase frequency
-- ------------------------------------------------------------------------------
SELECT 
    p.product_id,
    ROUND(AVG(oi.price), 2) AS avg_price,
    COUNT(oi.order_id) AS purchase_count
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id
ORDER BY purchase_count DESC;

-- ------------------------------------------------------------------------------
-- 10. Total revenue generated by each seller with revenue rank
-- ------------------------------------------------------------------------------
SELECT 
    s.seller_id,
    COALESCE(s.seller_city, 'N/A') AS seller_city,
    COALESCE(s.seller_state, 'N/A') AS seller_state,
    ROUND(SUM(oi.price), 2) AS total_revenue,
    DENSE_RANK() OVER (ORDER BY SUM(oi.price) DESC) AS revenue_rank
FROM sellers s
JOIN order_items oi ON s.seller_id = oi.seller_id
GROUP BY s.seller_id, s.seller_city, s.seller_state
ORDER BY total_revenue DESC;

-- ------------------------------------------------------------------------------
-- 11. Moving average of order values for each customer over order history
-- ------------------------------------------------------------------------------
SELECT 
    orders.customer_id, 
    orders.order_purchase_timestamp, 
    payments.payment_value AS payment,
    ROUND(AVG(payments.payment_value) OVER(
        PARTITION BY orders.customer_id 
        ORDER BY orders.order_purchase_timestamp 
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ), 2) AS moving_avg_order_value
FROM payments 
JOIN orders ON payments.order_id = orders.order_id;

-- ------------------------------------------------------------------------------
-- 12. Cumulative sales per month for each year
-- ------------------------------------------------------------------------------
WITH monthly_sales AS (
    SELECT 
        substr(o.order_purchase_timestamp, 1, 4) AS sale_year,
        substr(o.order_purchase_timestamp, 6, 2) AS sale_month,
        ROUND(SUM(p.payment_value), 2) AS monthly_revenue
    FROM orders o
    JOIN payments p ON o.order_id = p.order_id
    WHERE o.order_purchase_timestamp IS NOT NULL
    GROUP BY sale_year, sale_month
)
SELECT 
    sale_year,
    sale_month,
    monthly_revenue,
    ROUND(SUM(monthly_revenue) OVER (
        PARTITION BY sale_year 
        ORDER BY sale_month
    ), 2) AS cumulative_monthly_revenue
FROM monthly_sales
ORDER BY sale_year, sale_month;

-- ------------------------------------------------------------------------------
-- 13. Year-over-Year (YoY) growth rate of total sales
-- ------------------------------------------------------------------------------
WITH annual_sales AS (
    SELECT 
        substr(o.order_purchase_timestamp, 1, 4) AS order_year,
        ROUND(SUM(p.payment_value), 2) AS total_sales
    FROM orders o
    JOIN payments p ON o.order_id = p.order_id
    WHERE o.order_purchase_timestamp IS NOT NULL
    GROUP BY order_year
)
SELECT 
    order_year,
    total_sales,
    LAG(total_sales) OVER (ORDER BY order_year) AS previous_year_sales,
    ROUND(
        ((total_sales - LAG(total_sales) OVER (ORDER BY order_year)) * 100.0) / 
        LAG(total_sales) OVER (ORDER BY order_year), 2
    ) AS yoy_growth_percentage
FROM annual_sales
ORDER BY order_year;

-- ------------------------------------------------------------------------------
-- 14. Top 3 customers who spent the most money in each year
-- ------------------------------------------------------------------------------
WITH customer_yearly_spend AS (
    SELECT 
        substr(o.order_purchase_timestamp, 1, 4) AS spend_year,
        c.customer_unique_id,
        ROUND(SUM(p.payment_value), 2) AS total_spent,
        DENSE_RANK() OVER (
            PARTITION BY substr(o.order_purchase_timestamp, 1, 4) 
            ORDER BY SUM(p.payment_value) DESC
        ) AS rank_in_year
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    JOIN payments p ON o.order_id = p.order_id
    WHERE o.order_purchase_timestamp IS NOT NULL
    GROUP BY spend_year, c.customer_unique_id
)
SELECT 
    spend_year,
    customer_unique_id,
    total_spent,
    rank_in_year
FROM customer_yearly_spend
WHERE rank_in_year <= 3
ORDER BY spend_year, rank_in_year;
